# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
# 网站标题
title: Jesse-Kin`s blog
navbar:
  blog_title: Jesse的学习笔记
# 网站副标题
subtitle: ""
# 网站描述
description: ""
# 网站的关键字
keywords:
# 作者
author: Jesse Kin
# 语言
language:
  - zh-CN
  - en
# 时区
timezone: "Asia/Shanghai"

# URL
## Set your site url here. For example, if you use GitHub Page, set url as 'https://username.github.io/project'
# 网址
url: https://jesse-kin.github.io/
# 网站根目录
root: /
# 文章的永久链接格式
permalink: post/:abbrlink.html
abbrlink:
  alg: crc32 # 算法：crc16(default) and crc32
  rep: hex # 进制：dec(default) and hex
permalink_defaults:
# 改写 permalink 的值来美化 URL
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
# Source 文件夹 存储内容的位置
source_dir: source
# Public 文件夹 生成静态站点的位置
public_dir: public
# 标签文件夹
tag_dir: tags
# 归档文件夹
archive_dir: archives
# 分类文件夹
category_dir: categories
# Include code 文件夹， source_dir 下的子目录
code_dir: downloads/code
# 国际化（i18n）文件夹
i18n_dir: :lang
# 匹配到的文件将会被不做改动地复制到 public 目录中。 您可使用 glob 表达式来匹配路径。
skip_render:

# Writing
# 新文章的文件名称
new_post_name: :title.md # File name of new posts
# 预设布局
default_layout: post
# 把标题转换为 title case
titlecase: false # Transform title into titlecase
# 在新标签中打开链接
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ""
# 设置为 1 ，将文件名转换为小写形式； 设置为 2 ，将文件名转换为大写形式。
filename_case: 0
# 显示草稿
render_drafts: false
# 启用资源文件夹
post_asset_folder: true
# 把链接改为与根目录的相对位置
relative_link: false
# 显示未来的文章
future: true
# 代码块的设置
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: ""
  wrap: true
  hljs: false
# 代码块的设置
prismjs:
  enable: false
  preprocess: true
  line_number: true
  tab_replace: ""

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
# 生成帖子归档
index_generator:
  # 博客索引页面的根路径
  path: ""
  # 每页显示帖子数
  per_page: 10
  # 帖子排列顺序。 默认情况下按日期降序(从新到旧)。
  order_by: -date

# Category & Tag
# 默认分类
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
# 日期格式
date_format: YYYY-MM-DD
# 时间格式
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
# 当 Front Matter 中没有指定 updated 时 updated 的取值
updated_option: "date"

# Pagination
## Set per_page to 0 to disable pagination
# 每页显示的帖子数。 0 关闭分页功能
per_page: 0
# URL 格式
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
# 当前主题名称。 值为false时禁用主题
theme: next

# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
# 部署部分的设置
deploy:
  type: git
  # repo: https://github.com/Jesse-Kin/Jesse-Kin.github.io.git
  repo: git@github.com:Jesse-Kin/Jesse-Kin.github.io.git
  # repo: git@github.com:Jesse-Kin/github-blog.git
  branch: main
  message: "Site updated: {{ now('YYYY-MM-DD HH:mm:ss') }}"

# 添加搜索功能
search:
  path: search.json #之前就是这里出了问题导致图标错误，错误的教程是 search.xml
  field: post
  format: html
  limit: 1000

prism_plugin:
  mode: "preprocess" # realtime/preprocess
  theme: "default" # Prism.js 主题
  line_number: false # 显示行号
  exclude_languages: [] # 排除的语言
